-- Keep the task scheduler bounded to the dates a staff member is working in.
-- This function is SECURITY INVOKER, so kennel_records RLS remains in force.
create or replace function public.kennel_scheduled_care_tasks_window(
  p_start_date date,
  p_end_date date,
  p_since_updated_at timestamptz default null
)
returns table (
  id text,
  type text,
  payload jsonb,
  helper_email text,
  user_id uuid,
  submitted_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  with ranked_tasks as (
    select
      kr.id,
      kr.type,
      kr.payload,
      kr.helper_email,
      kr.user_id,
      kr.submitted_at,
      kr.updated_at,
      row_number() over (
        partition by case
          when coalesce(lower(kr.payload ->> 'autoGenerated'), 'false') = 'true'
            and coalesce(lower(kr.payload ->> 'status'), '') not in ('completed', 'cancelled')
            and nullif(kr.payload ->> 'sourceKey', '') is not null
          then 'auto:' || (kr.payload ->> 'sourceKey')
          else 'row:' || kr.id
        end
        order by
          (coalesce(lower(kr.payload ->> 'sourceManualOverride'), 'false') = 'true') desc,
          kr.updated_at desc,
          kr.submitted_at desc,
          kr.id desc
      ) as source_rank
    from public.kennel_records kr
    where kr.type = 'scheduledCareTask'
      and coalesce(lower(kr.payload ->> 'removed'), 'false') <> 'true'
      and kr.payload ->> 'date' >= p_start_date::text
      and kr.payload ->> 'date' <= p_end_date::text
  )
  select
    ranked.id,
    ranked.type,
    ranked.payload,
    ranked.helper_email,
    ranked.user_id,
    ranked.submitted_at,
    ranked.updated_at
  from ranked_tasks ranked
  where ranked.source_rank = 1
    and (p_since_updated_at is null or ranked.updated_at >= p_since_updated_at)
  order by ranked.updated_at desc
  limit 5000;
$$;

revoke all on function public.kennel_scheduled_care_tasks_window(date, date, timestamptz) from public;
revoke all on function public.kennel_scheduled_care_tasks_window(date, date, timestamptz) from anon;
grant execute on function public.kennel_scheduled_care_tasks_window(date, date, timestamptz) to authenticated;
grant execute on function public.kennel_scheduled_care_tasks_window(date, date, timestamptz) to service_role;

create index if not exists kennel_records_active_scheduled_task_date_updated_idx
  on public.kennel_records ((payload ->> 'date'), updated_at desc)
  where type = 'scheduledCareTask'
    and coalesce(lower(payload ->> 'removed'), 'false') <> 'true';
